### ISSUE TITLE
Texte corrections

### ISSUE THREAD

**Issue by Elfennacht** [TwiceCast/swagger#1]
### GET/users/{user_id}/friends

> Responses
> Code	Description
> 200		This will contain your users, this result will be split. You must recall this route by incrementing start of x times limit. x is the number of page that you want. If you ask for a**n** out of range value, you will have a 404 error.

### DELETE/users/{user_id}

> Responses
> Code	Description
> 204		The user has been remove**d** successfully.

### PUT/users/{user_id}/avatar

> Parameters
> Name	Description
> avatar	Avatar is an image, if possible we want a png image. With a s**qu**are as ratio.

**Comment by Stargateur** [comment]
https://github.com/TwiceCast/swagger/commit/4a44488286981140867ea453ce00c8d665b74b0d
